name: dogs

dependencies:
  - python=2.7
  - h5py
  - scipy
  - numpy
  - pandas
  - matplotlib=1.4.3
  - seaborn
  - pip:
    - alabaster==0.7.4
    - appnope==0.1.0
    - Babel==1.3
    - backports-abc==0.4
    - backports.ssl-match-hostname==3.5.0.1
    - biom-format==2.1.4
    - burrito==0.9.1
    - burrito-fillings==0.1.1
    - certifi==2016.2.28
    - cogent==1.5.3
    - Cython==0.22
    - decorator==4.0.9
    - docutils==0.12
    - emperor
    - functools32==3.2.3.post2
    - future==0.14.3
    - gdata==2.0.18
    - gnureadline==6.3.3
    - h5py==2.5.0
    - igraph==0.1.8
    - ipykernel==4.3.1
    - ipython==4.1.2
    - ipython-genutils==0.1.0
    - ipywidgets==4.1.1
    - Jinja2==2.8
    - jsonschema==2.5.1
    - jupyter==1.0.0
    - jupyter-client==4.2.2
    - jupyter-console==4.1.1
    - jupyter-core==4.1.0
    - MarkupSafe==0.23
    - mistune==0.7.2
    - mock==1.0.1
    - natsort==3.5.6
    - nbconvert==4.1.0
    - nbformat==4.0.1
    - networkx==1.10
    - nose==1.3.7
    - notebook==4.1.0
    - numpydoc==0.5
    - path.py==8.1.2
    - patsy==0.4.0
    - pexpect==4.0.1
    - pickleshare==0.6
    - ptyprocess==0.5.1
    - Pygments==2.1.3
    - pynast==1.2.2
    - pyparsing==2.0.3
    - pyqi==0.3.2
    - python-dateutil==2.4.2
    - pytz==2015.7
    - pyzmq==15.2.0
    - qcli==0.1.1
    - qiime==1.9.1
    - qiime-default-reference==0.1.2
    - qtconsole==4.2.1
    - requests==2.7.0
    - rpy2==2.7.4
    - scikit-bio==0.2.3
    - seaborn==0.6.0
    - simplegeneric==0.8.1
    - singledispatch==3.4.0.3
    - six==1.10.0
    - snowballstemmer==1.2.0
    - Sphinx==1.3.1
    - sphinx-rtd-theme==0.1.8
    - statsmodels==0.6.1
    - terminado==0.6
    - tornado==4.3
    - traitlets==4.2.1
    - xlrd==0.9.4

